---
messagerie:
  :nom: messagerie
  :url: http://www.perdu.com
validationcompetences:
  :nom: validation de competences
  :url: http://www.perdu.com
trombi:
  :nom: trombinoscope
  :url: http://www.perdu.com
admin:
  :nom: administration
  :url: http://www.perdu.com
documents:
  :nom: documents
  :url: http://www.perdu.com
thematiques:
  :nom: thématiques
  :url: http://www.perdu.com
suivi:
  :nom: suivi des élèves
  :url: http://www.perdu.com
cahierdetextes:
  :nom: cahier de textes
  :url: http://localhost:9293/ct/
blogs:
  :nom: blogs
  :url: http://www.perdu.com
publipostage:
  :nom: info familles
  :url: http://www.perdu.com
notesabsences:
  :nom: notes et absences
  :url: http://www.perdu.com
ressources:
  :nom: ressources numériques
  :url: http://www.perdu.com
aide:
  :nom: aide
  :url: http://www.perdu.com
