---
:url_news: http://xkcd.com/rss.xml
:apps_tiles:
  messagerie:
    :index: 1
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/01_messagerie.svg"
    :couleur: bleu
    :notifications: []
    :nom: 'messagerie'
    :lien: "/portail/#/show-app?app=messagerie"
    :url: http://www.perdu.com
    :active: true
  DOC:
    :index: 2
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/02_documents.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :lien: ''
    :active: false
  CTXT:
    :index: 3
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/03_cahierdetextes.svg"
    :couleur: violet
    :notifications: []
    :nom: ''
    :lien: ''
    :active: false
  notesabsences:
    :index: 4
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/04_notesabsences.svg"
    :couleur: vert
    :notifications: []
    :nom: ''
    :lien: ''
    :active: false
  validationcompetences:
    :index: 5
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/05_validationcompetences.svg"
    :couleur: rouge
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  thematiques:
    :index: 6
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/06_thematiques.svg"
    :couleur: vert
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  blogs:
    :index: 7
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/07_blogs.svg"
    :couleur: bleu
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  ressources:
    :index: 8
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/08_ressources.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  trombi:
    :index: 9
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/09_trombi.svg"
    :couleur: violet
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  SUIVIELV:
    :index: 10
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/10_suivi.svg"
    :couleur: bleu
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  Publi:
    :index: 11
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/11_publipostage.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  aide:
    :index: 12
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/12_aide.svg"
    :couleur: rouge
    :notifications: []
    :active: true
    :nom: aide
    :lien: "/portail/#/show-app?app=aide"
    :url: http://www.perdu.com
  admin:
    :index: 13
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/13_admin.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  empty1:
    :index: 14
    :icone: ''
    :couleur: rouge
    :notifications: []
    :nom: ''
    :lien: ''
    :url: ''
    :active: true
  empty2:
    :index: 15
    :icone: ''
    :couleur: vert
    :notifications: []
    :nom: ''
    :lien: ''
    :url: ''
    :active: true
  empty3:
    :index: 16
    :icone: ''
    :couleur: orange
    :notifications: []
    :nom: ''
    :lien: ''
    :url: ''
    :active: true
