---
:url_news: http://xkcd.com/rss.xml
:apps:
  messagerie:
    :nom: messagerie
    :url: http://www.perdu.com
  validationcompetences:
    :nom: validation de competences
    :url: http://www.perdu.com
  trombi:
    :nom: trombinoscope
    :url: http://www.perdu.com
  admin:
    :nom: administration
    :url: http://www.perdu.com
  thematiques:
    :nom: thématiques
    :url: http://www.perdu.com
  blogs:
    :nom: blogs
    :url: http://www.perdu.com
  notesabsences:
    :nom: notes et absences
    :url: http://www.perdu.com
  ressources:
    :nom: ressources numériques
    :url: http://www.perdu.com
  aide:
    :nom: aide
    :url: http://www.perdu.com
:apps_tiles:
  messagerie:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/01_messagerie.svg"
    :couleur: bleu
    :notifications: []
    :active: false
  DOC:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/02_documents.svg"
    :couleur: jaune
    :notifications: []
    :active: false
  CTXT:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/03_cahierdetextes.svg"
    :couleur: violet
    :notifications: []
    :active: false
  notesabsences:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/04_notesabsences.svg"
    :couleur: vert
    :notifications: []
    :active: false
  validationcompetences:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/05_validationcompetences.svg"
    :couleur: rouge
    :notifications: []
    :active: false
  thematiques:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/06_thematiques.svg"
    :couleur: vert
    :notifications: []
    :active: false
  blogs:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/07_blogs.svg"
    :couleur: bleu
    :notifications: []
    :active: false
  ressources:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/08_ressources.svg"
    :couleur: jaune
    :notifications: []
    :active: false
  trombi:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/09_trombi.svg"
    :couleur: violet
    :notifications: []
    :active: false
  SUIVIELV:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/10_suivi.svg"
    :couleur: bleu
    :notifications: []
    :active: false
  Publi:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/11_publipostage.svg"
    :couleur: jaune
    :notifications: []
    :active: false
  aide:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/12_aide.svg"
    :couleur: rouge
    :notifications: []
    :active: true
    :nom: aide
    :lien: "/portail/#/show-app?app=aide"
  admin:
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/13_admin.svg"
    :couleur: jaune
    :notifications: []
    :active: false
  empty1:
    :icone: ''
    :couleur: rouge
    :notifications: []
    :active: true
  empty2:
    :icone: ''
    :couleur: vert
    :notifications: []
    :active: true
  empty3:
    :icone: ''
    :couleur: orange
    :notifications: []
    :active: true
  empty4:
    :icone: ''
    :couleur: violet
    :notifications: []
    :active: true
  empty5:
    :icone: ''
    :couleur: vert
    :notifications: []
    :active: true
  empty6:
    :icone: ''
    :couleur: jaune
    :notifications: []
    :active: true
  empty7:
    :icone: ''
    :couleur: bleu
    :notifications: []
    :active: true
