---
:url_news: http://xkcd.com/rss.xml
:apps_tiles:
  MAIL:
    :index: 1
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/01_messagerie.svg"
    :couleur: bleu
    :notifications: []
    :nom: 'messagerie'
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  DOC:
    :index: 2
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/02_documents.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :survol: ''
    :active: false
  CTXT:
    :index: 3
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/03_cahierdetextes.svg"
    :couleur: violet
    :notifications: []
    :nom: ''
    :survol: ''
    :active: false
  TELESRV:
    :index: 4
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/04_notesabsences.svg"
    :couleur: vert
    :notifications: []
    :nom: ''
    :survol: ''
    :active: false
  LPC:
    :index: 5
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/05_validationcompetences.svg"
    :couleur: rouge
    :notifications: []
    :nom: ''
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  CCNUM:
    :index: 6
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/06_thematiques.svg"
    :couleur: vert
    :notifications: []
    :nom: ''
    :survol: ''
    :url: ''
    :active: false
  BLOGS:
    :index: 7
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/07_blogs.svg"
    :couleur: bleu
    :notifications: []
    :nom: ''
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  GAR:
    :index: 8
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/08_ressources.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  TROMBI:
    :index: 9
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/09_trombi.svg"
    :couleur: violet
    :notifications: []
    :nom: ''
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  SUIVIELV:
    :index: 10
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/10_suivi.svg"
    :couleur: bleu
    :notifications: []
    :nom: ''
    :survol: ''
    :lien: ''
    :url: http://www.perdu.com
    :active: false
  Publi:
    :index: 11
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/11_publipostage.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  AIDE:
    :index: 12
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/12_aide.svg"
    :couleur: rouge
    :notifications: []
    :active: true
    :nom: aide
    :survol: 'Aide en ligne'
    :url: http://www.perdu.com
  ADMIN:
    :index: 13
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/13_admin.svg"
    :couleur: jaune
    :notifications: []
    :nom: ''
    :survol: ''
    :url: http://www.perdu.com
    :active: false
  PRONOTE:
    :index: 14
    :icone: "/app/bower_components/charte-graphique-laclasse-com/images/04_notesabsences.svg"
    :couleur: rouge
    :notifications: []
    :nom: ''
    :survol: ''
    :url: '#'
    :active: true
  empty2:
    :index: 15
    :icone: ''
    :couleur: vert
    :notifications: []
    :nom: ''
    :survol: ''
    :url: '#'
    :active: true
  empty3:
    :index: 16
    :icone: ''
    :couleur: orange
    :notifications: []
    :nom: ''
    :survol: ''
    :url: '#'
    :active: true
